Repository 2022-Alpha-Daesin/daesin_back, pull requests merged in 2022-11, with the labels that each got.

#16 chore: swagger 설정
  docker-compose.yml
  webapp/requirements.txt
  webapp/webapp/settings.py
  webapp/webapp/urls.py
Labels: enhancement

#21 feat: Usermodel 생성
  webapp/user/__init__.py
  webapp/user/admin.py
  webapp/user/apps.py
  webapp/user/migrations/0001_initial.py
  webapp/user/migrations/__init__.py
  webapp/user/models.py
  webapp/user/views.py
  webapp/webapp/settings.py
Labels: enhancement

#18 chore: docker 빌드시 collect static 진행 하도록 수정
  docker-compose.yml
Labels: enhancement

#24 Feature/7 user login registration
  webapp/requirements.txt
  webapp/templates/account/email/email_confirmation_signup_message.html
  webapp/templates/account/email/email_confirmation_subject.txt
  webapp/user/adapter.py
  webapp/user/admin.py
  webapp/user/models.py
  webapp/user/serializers.py
  webapp/user/views.py
  webapp/webapp/settings.py
  webapp/webapp/urls.py
Labels: enhancement

#28 fix: timezone 오타 수정
  webapp/webapp/settings.py
Labels: bug

#31 feature/30-csrf
  webapp/user/serializers.py
  webapp/webapp/authentications.py
  webapp/webapp/settings.py
  webapp/webapp/urls.py
Labels: enhancement

#32 Feature/29 modify user url
  webapp/webapp/urls.py
Labels: refactor

#38 chore: docker개발 환경 uwsgi->runserver nginx app.sock이 아닌 8000포트 바인딩 roo…
  .gitignore
  docker-compose.yml
  nginx/Dockerfile
  nginx/Dockerfile.production
  nginx/develop/nginx-app.conf
  nginx/develop/nginx.conf
  nginx/production/nginx-app.conf
  nginx/production/nginx.conf
  webapp/Dockerfile
  webapp/requirements.txt
  webapp/webapp/settings.py
  webapp/webapp/urls.py
Labels: bug

#46 Feature/45 login fix
  webapp/user/admin.py
  webapp/user/serializers.py
  webapp/webapp/settings.py
Labels: enhancement

#43 fix: post model 요구사항 수정
  webapp/post/migrations/0002_alter_post_type.py
  webapp/post/models.py
Labels: enhancement

#50 feat: 학과 정보 크롤링 커맨드 개발
  webapp/post/migrations/0003_merge_0002_alter_post_type_0002_initial.py
  webapp/requirements.txt
  webapp/user/management/commands/__init__.py
  webapp/user/management/commands/pull_major.py
  webapp/user/migrations/0003_alter_major_department_alter_major_sub_major.py
  webapp/user/models/major.py
Labels: enhancement

#67 feature:add club logic at advertisement app
  webapp/ad/migrations/0003_advertisement_club_advertisement_is_club.py
  webapp/ad/migrations/0004_remove_advertisement_is_club.py
  webapp/ad/models/advertisement.py
  webapp/ad/serializers/ad_serializer.py
  webapp/club/admin.py
  webapp/config/urls.py
Labels: enhancement

#71 feature: relationship app 구현(좋아요, 스크랩, 댓글)
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/post/models/post.py
  webapp/post/serializers/post_serializer.py
  webapp/relationship/__init__.py
  webapp/relationship/admin.py
  webapp/relationship/apps.py
  webapp/relationship/migrations/0001_initial.py
  webapp/relationship/migrations/0002_alter_comment_created_at_alter_comment_parent_and_more.py
  webapp/relationship/migrations/0003_alter_like_post.py
  webapp/relationship/migrations/0004_alter_like_post.py
  webapp/relationship/migrations/__init__.py
  webapp/relationship/models/__init__.py
  webapp/relationship/models/comment.py
  webapp/relationship/models/like.py
  webapp/relationship/models/scrap.py
  webapp/relationship/serializers/__init__.py
  webapp/relationship/serializers/comment_serializer.py
  webapp/relationship/serializers/like_serializer.py
  webapp/relationship/serializers/scrap_serializer.py
  webapp/relationship/tests.py
  webapp/relationship/urls/comment.py
  webapp/relationship/urls/like.py
  webapp/relationship/urls/scrap.py
  webapp/relationship/views/__init__.py
  webapp/relationship/views/comment_view_set.py
  webapp/relationship/views/like_view_set.py
  webapp/relationship/views/scrap_view_set.py
  webapp/user/management/commands/pull_major.py
Labels: enhancement

#73 feature:user detail and detail modify
  webapp/config/settings/base.py
  webapp/user/serializers/__init__.py
  webapp/user/serializers/custom_user_detail_serializer.py
  webapp/user/serializers/user_major_serializer.py
  webapp/user/views/user_major_view.py
Labels: enhancement

#69 chore: local 에서 was로 gunicorn 설정
  docker-compose.production.yml
  nginx/develop/nginx-app.conf
  webapp/config/urls.py
Labels: enhancement

#76 feature: gunicorn nginx 배포환경에서 연결 및 배포 환경 분리
  README.md
  docker-compose.production.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/Dockerfile.production
  nginx/develop/docker-entrypoint.sh
  nginx/develop/nginx-app.conf
  nginx/develop/nginx.conf
  nginx/production/docker-entrypoint.production.sh
  nginx/production/nginx-app.conf
  nginx/production/nginx.conf
  nginx/wait-for-it.sh
  webapp/Dockerfile
  webapp/Dockerfile.production
  webapp/ad/migrations/0001_initial.py
  webapp/ad/migrations/0002_initial.py
  webapp/ad/migrations/0003_advertisement_club_advertisement_is_club.py
  webapp/ad/migrations/0004_remove_advertisement_is_club.py
  webapp/club/migrations/0001_initial.py
  webapp/club/migrations/0002_initial.py
  webapp/config/settings/base.py
  webapp/config/settings/prod.py
  webapp/docker-entrypoint.production.sh
  webapp/docker-entrypoint.sh
  webapp/post/migrations/0001_initial.py
  webapp/post/migrations/0002_initial.py
  webapp/relationship/migrations/0001_initial.py
  webapp/relationship/migrations/0002_alter_comment_created_at_alter_comment_parent_and_more.py
  webapp/relationship/migrations/0003_alter_like_post.py
  webapp/relationship/migrations/0004_alter_like_post.py
  webapp/review/migrations/0001_initial.py
  webapp/user/management/commands/pull_major.py
  webapp/user/migrations/0001_initial.py
  webapp/uwsgi.ini
Labels: enhancement

#78 hotfix:usermajor 생성 안되는 문제 해결
  docker-compose.yml
  webapp/ad/migrations/0001_initial.py
  webapp/ad/migrations/0002_initial.py
  webapp/ad/migrations/0003_initial.py
  webapp/club/migrations/0001_initial.py
  webapp/club/migrations/0002_initial.py
  webapp/post/migrations/0001_initial.py
  webapp/post/migrations/0002_initial.py
  webapp/relationship/migrations/0001_initial.py
  webapp/relationship/migrations/0002_initial.py
  webapp/review/migrations/0001_initial.py
  webapp/user/adapter.py
  webapp/user/migrations/0001_initial.py
Labels: bug

#77 Feature/75 post image
  webapp/ad/models/advertisement.py
  webapp/ad/serializers/__init__.py
  webapp/ad/serializers/ad_serializer.py
  webapp/ad/serializers/list_serializer.py
  webapp/ad/views/ad_viewset.py
  webapp/config/settings/base.py
  webapp/config/urls.py
  webapp/docker-entrypoint.production.sh
  webapp/docker-entrypoint.sh
  webapp/post/serializers/__init__.py
  webapp/post/serializers/image_serializer.py
  webapp/post/serializers/post_serializer.py
  webapp/post/views/__init__.py
  webapp/post/views/image_viewset.py
  webapp/review/models/review.py
  webapp/review/serializers/__init__.py
  webapp/review/serializers/list_serializer.py
  webapp/review/serializers/review_serializer.py
  webapp/review/views/review_viewset.py
  webapp/tag/__init__.py
  webapp/tag/admin.py
  webapp/tag/apps.py
  webapp/tag/management/commands/__init__.py
  webapp/tag/management/commands/init_tags.py
  webapp/tag/migrations/0001_initial.py
  webapp/tag/migrations/0002_alter_tag_content.py
  webapp/tag/migrations/__init__.py
  webapp/tag/models/__init__.py
  webapp/tag/models/club_tag.py
  webapp/tag/models/post_tag.py
  webapp/tag/models/tag.py
  webapp/tag/serializers/__init__.py
  webapp/tag/serializers/club_tag.py
  webapp/tag/serializers/post_tag.py
  webapp/tag/serializers/tag.py
  webapp/tag/tests.py
  webapp/tag/urls.py
  webapp/tag/views/__init__.py
  webapp/tag/views/views.py
Labels: enhancement

#83 feature:my_post and scrap_post
  webapp/ad/migrations/0004_alter_advertisement_options.py
  webapp/post/views/post_viewset.py
  webapp/relationship/admin.py
  webapp/review/migrations/0002_alter_review_options.py
Labels: enhancement
